/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restapi;

import static spark.Spark.*;

import spark.Request;
import spark.Response;
import spark.Route;

public class App {
    public static void main(String[] args) {
        ProcessBuilder process = new ProcessBuilder();
        Integer PORT;
        if (process.environment().get("PORT") != null) {
            PORT = Integer.parseInt(process.environment().get("PORT"));
        } else {
            PORT = 5000;
        }
        port(PORT);

        get("/hello", new Route() {
            @Override
            public Object handle(Request request, Response response) throws Exception {
                return "world of java";
            }
        });
    }
}
